// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// ==/ClosureCompiler==
var Colors={Back:"#000",Border:"#222",UI:"#777",Beam:"#F00",Text:"#CCC",Node:["#333","#242","#422"],AfterImageFore:"#FF0",AfterImageBack:"#800",Filter:"#5F2",Shooter:"#888",Dropper:"#555",Shot:"#CCC",ShadowX:0,ShadowY:3,ShadowR:5},Settings={BackDrawer:{Background:Colors.Back,Alpha:.8,Border:Colors.Border,TextColor:Colors.UI,MarginLeft:.5,MarginRight:.5},Background:{FPSspan:10,FPS:[50,65],DisableCount:10},Dropper:{MoveSpeed:4,SpeedUpLevel:300,SpeedUpSpeed:31,MaxSpeed:9,TurnProbability:.4,DropProbability:.2,
Color:Colors.Dropper},Shotter:{Beam:{BlinkSpeed:100,Color:Colors.Beam},Y:28,MoveSpeed:.5,Color:Colors.Shooter,Keymap:[37,39,38,72],KeySleepMax1:[9,9,21,Infinity],KeySleepMax2:[3,3,9,Infinity]},Shots:{Radius:.2,Color:Colors.Shot,MoveSpeed:.5},NumNodes:{LevelToMaxWeighting:7,Colors:Colors.Node,MaxFactCount:6,MoveSpeed:.02,TextColor:Colors.Text,minNumber:10},AfterImages:{ShowTicks:100,MaxAlpha:.7,Fore:Colors.AfterImageFore,Back:Colors.AfterImageBack},Filters:{Color:Colors.Filter},ButtonNodes:{Color:Colors.Node[0],
TextColor:Colors.Text},Fading:{Speed:100,Color:Colors.Back},onTick:{HintperLevel:13,FilterperLevel:97},Game:{Wcount:9,Hcount:32,Wcell:34,Hcell:20,Rcell:5,FontName:'"Kokoro", "Rounded Mplus 1c", "Open Sans", "Noto Sans Japanese", "Yu Gothic", "Meiryo UI", sans-serif',life:5},ResizingCanvas:{Margin:10,shadowBlur:Colors.ShadowR,shadowColor:"#000",shadowOffsetX:Colors.ShadowX,shadowOffsetY:Colors.ShadowY},ScoreAndLevel:function(a,c){var b=0==Factorization(c)[0];switch(a){case 0:Game.score+=7*c;Game.level+=
7;break;case 1:b?(Game.score+=11*c,Game.level+=11):(Game.score-=17*c,Game.level-=17,Game.life--);break;case 2:b?(Game.score-=31*c,Game.level-=31,Game.life-=3):(Game.score+=c,Game.level++)}}},Polyfill;(function(a){a.Do=function(){var a=void 0,b=function(b){"number"==typeof a&&clearTimeout(a);a=setTimeout(b,1E3/60)};window.requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||b}})(Polyfill||(Polyfill={}));
function GetTime(){var a=window.performance&&performance.now;return a&&a.call(performance)||(new Date).getTime()}function Factorization(a){if(0==a%2&&2!=a)return[2,a/2];for(var c=3;c<a;c+=2)if(0===a%c)return[c,a/c];return[0,a]}var TrafficBackground;
(function(a){function c(a,b){return Math.random()*(b-a)+a}var b="c1",d=[.7,1],e=[3,2],f=1,g=function(a,b){var c=this;this.Parent=b;if(a.getContext)this.ctx=a.getContext("2d");else throw"Canvas\u304c\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u3088\u3046\u3067\u3059\u3002Chrome\u3084Chrome\u306a\u3069\u306e\u30ca\u30a6\u3044\u30d6\u30e9\u30a6\u30b6\u30fc\u3092\u4f7f\u3044\u306a\u3055\u3044";var f=this;(function(a){var b=!1;window.addEventListener("resize",function(){"number"==typeof b&&clearTimeout(b);
b=setTimeout(a,100)})})(function(){return c.OnResize.call(f)});this.scaleY=this.scaleX=1;this.OnResize()};g.prototype.OnResize=function(){var a=this.ctx.canvas;this.scaleX=this.Parent.clientWidth;this.scaleY=this.Parent.clientHeight;a.style.width=this.scaleX+"px";a.style.height=this.scaleY+"px";this.scaleX*=(window.devicePixelRatio||1)/f;this.scaleY*=(window.devicePixelRatio||1)/f;a.width=this.scaleX;a.height=this.scaleY;this.ctx.lineWidth=(window.devicePixelRatio||1)/f*1};g.prototype.Sx=function(a){return a*
this.scaleX};g.prototype.Sy=function(a){return a*this.scaleY};g.prototype.Line=function(a,b,c,f){this.ctx.beginPath();this.ctx.moveTo(this.Sx(a),this.Sy(b));this.ctx.lineTo(this.Sx(c),this.Sy(f));this.ctx.stroke()};var l=function(){this.Name="Dots";this.Enabled=!0;this.cities=[];this.cars=[]};l.prototype.Init=function(a){a.ctx.globalCompositeOperation="source-over";a.ctx.fillStyle="#000";a.ctx.fillRect(0,0,a.Sx(1),a.Sy(1));for(var b=0;50>b;b++){var f=c(d[0],d[1]),h=c(0,2*Math.PI);this.cities.push({x:Math.random(),
y:Math.random(),dx:f*Math.cos(h),dy:f*Math.sin(h),hue:12*Math.random()<<0})}for(b=0;500>b;b++)f=c(0,50)<<0,h=this.GetNeightbor(a,this.cities[f].x,this.cities[f].y,c(1,4)<<0),this.cars.push({x:this.cities[f].x,y:this.cities[f].y,speed:c(e[0],e[1]),hue:this.cities[f].hue,to:h});return this};l.prototype.Draw=function(a,b){for(var e=0;e<this.cities.length;e++){var d=this.cities[e];d.x+=d.dx/a.Sx(1)/f;d.y+=d.dy/a.Sy(1)/f;1<d.x?(d.dx=-d.dx,d.hue+=1):0>d.x&&(d.dx=-d.dx,d.hue+=1);1<d.y?(d.dy=-d.dy,d.hue+=
1):0>d.y&&(d.dy=-d.dy,d.hue+=1);d.hue%=12}a.ctx.globalAlpha=.1;a.ctx.globalCompositeOperation="source-over";a.ctx.fillStyle="#000";a.ctx.fillRect(0,0,a.Sx(1),a.Sy(1));a.ctx.globalAlpha=.3;a.ctx.globalCompositeOperation="lighter";for(e=0;12>e;e++){a.ctx.strokeStyle="hsl("+30*e+", 80%,70%)";a.ctx.beginPath();for(d=0;d<this.cars.length;d++){var g=this.cars[d];if(g.hue==e)if(Math.pow(a.Sx(g.x-this.cities[g.to].x),2)+Math.pow(a.Sy(g.y-this.cities[g.to].y),2)<Math.pow(g.speed/f,2)){a.ctx.moveTo(a.Sx(g.x)<<
0,a.Sy(g.y)<<0);a.ctx.lineTo(a.Sx(this.cities[g.to].x)<<0,a.Sy(this.cities[g.to].y)<<0);this.cities[g.to].hue=(this.cities[g.to].hue+(.01>Math.random()?1:0))%12;var h=this.GetNeightbor(a,this.cities[g.to].x,this.cities[g.to].y,c(1,4)<<0);this.cars[d]={x:this.cities[g.to].x,y:this.cities[g.to].y,speed:g.speed,hue:this.cities[g.to].hue,to:h}}else{var h=[this.cities[g.to].x-g.x,this.cities[g.to].y-g.y],l=Math.sqrt(Math.pow(a.Sx(h[0]),2)+Math.pow(a.Sy(h[1]),2))*f;h[0]*=g.speed/l;h[1]*=g.speed/l;a.ctx.moveTo(a.Sx(g.x)<<
0,a.Sy(g.y)<<0);a.ctx.lineTo(a.Sx(g.x+h[0])<<0,a.Sy(g.y+h[1])<<0);this.cars[d].x+=h[0];this.cars[d].y+=h[1]}}a.ctx.stroke()}};l.prototype.GetNeightbor=function(a,b,f,c){for(var d=Array(this.cities.length),e=0;e<this.cities.length;e++)d[e]=Math.sqrt(Math.pow(a.Sx(this.cities[e].x-b),2)+Math.pow(a.Sy(this.cities[e].y-f),2));a=new Set;b=Infinity;for(var g=f=0;g<=c;g++){for(e=0;e<d.length;e++)!a.has(e)&&b>d[e]&&(b=d[e],f=e);a.add(f);b=Infinity}return f};var k;(function(a){a.Init=function(){a.c1=new g(document.getElementById(b),
document.documentElement);a.Elm=(new l).Init(a.c1)};var f=void 0,d=0;a.Tick=function(b){-1<d++&&(d=0,void 0===f&&(f=b),a.Elm.Draw(a.c1,b-f),f=b)}})(k||(k={}));a.Init=function(a){b=a;k.Init()};a.Tick=function(){k.Tick(GetTime())};a.GetDPI=function(){return f};a.SetDPI=function(a){f=a;k.c1.OnResize()}})(TrafficBackground||(TrafficBackground={}));
var ResizingCanvas=function(a,c,b,d){var e=this;this.Parent=c;if(a.getContext)this.ctx=a.getContext("2d");else throw"Canvas\u304c\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u3088\u3046\u3067\u3059\u3002Chrome\u3084Chrome\u306a\u3069\u306e\u30ca\u30a6\u3044\u30d6\u30e9\u30a6\u30b6\u30fc\u3092\u4f7f\u3044\u306a\u3055\u3044";var f=this;(function(a){var b=!1;window.addEventListener("resize",function(){"number"==typeof b&&clearTimeout(b);b=setTimeout(a,100)})})(function(){return e.OnResize.call(f)});this.width=
b;this.height=d;this.OnResize()};ResizingCanvas.prototype.OnResize=function(a){var c=this.ctx.canvas,b=Math.min((this.Parent.clientWidth-Settings.ResizingCanvas.Margin)/this.width,(this.Parent.clientHeight-Settings.ResizingCanvas.Margin)/this.height);c.style.width=b*this.width+"px";c.style.height=b*this.height+"px";b*=a||window.devicePixelRatio||1;c.width=b*this.width;c.height=b*this.height;this.ctx.lineWidth=a||window.devicePixelRatio||1;this.scale=b};
ResizingCanvas.prototype.S=function(a){return a*this.scale};ResizingCanvas.prototype.Line=function(a,c,b,d){this.ctx.beginPath();this.ctx.moveTo(this.S(a+.5),this.S(c+.5));this.ctx.lineTo(this.S(b+.5),this.S(d+.5));this.ctx.stroke()};ResizingCanvas.prototype.Round=function(a,c,b){this.ctx.arc(this.S(a),this.S(c),this.S(b),0,2*Math.PI,!1)};
ResizingCanvas.prototype.RoundedRect=function(a,c,b,d,e){a=this.S(a);c=this.S(c);b=this.S(b);d=this.S(d);e=this.S(e);this.ctx.moveTo(a,c+e);this.ctx.lineTo(a,c+d-e);this.ctx.quadraticCurveTo(a,c+d,a+e,c+d);this.ctx.lineTo(a+b-e,c+d);this.ctx.quadraticCurveTo(a+b,c+d,a+b,c+d-e);this.ctx.lineTo(a+b,c+e);this.ctx.quadraticCurveTo(a+b,c,a+b-e,c);this.ctx.lineTo(a+e,c);this.ctx.quadraticCurveTo(a,c,a,c+e)};
ResizingCanvas.prototype.TextCenter=function(a,c,b,d){this.ctx.textAlign="center";this.ctx.textBaseline="middle";this.ctx.fillText(a,this.S(c),this.S(b),this.S(d))};ResizingCanvas.prototype.TextLeft=function(a,c,b,d){this.ctx.textAlign="left";this.ctx.textBaseline="middle";this.ctx.fillText(a,this.S(c),this.S(b),this.S(d))};ResizingCanvas.prototype.TextRight=function(a,c,b,d){this.ctx.textAlign="right";this.ctx.textBaseline="middle";this.ctx.fillText(a,this.S(c),this.S(b),this.S(d))};
ResizingCanvas.prototype.Shadow=function(){this.ctx.shadowBlur=this.S(Settings.ResizingCanvas.shadowBlur);this.ctx.shadowColor=Settings.ResizingCanvas.shadowColor;this.ctx.shadowOffsetX=this.S(Settings.ResizingCanvas.shadowOffsetX);this.ctx.shadowOffsetY=this.S(Settings.ResizingCanvas.shadowOffsetY)};var Background=function(){this.Name="Background";this.Enabled=!0;this.BeforeOpe=this.FPSspan=this.FPScount=0;this.Countdown2Disable=Settings.Background.DisableCount};
Background.prototype.Init=function(a){TrafficBackground.Init(a);this.BeforeOpe=this.FPSspan=this.FPScount=0;return this};
Background.prototype.Draw=function(a,c){this.FPSspan+=c;if(this.FPScount++>Settings.Background.FPSspan){var b=1E3/(this.FPSspan/this.FPScount);b<Settings.Background.FPS[0]?(1==this.BeforeOpe?(console.log((b<<0)+"FPS-- => DPIfactor: "+(10*(TrafficBackground.GetDPI()-.1)<<0)),TrafficBackground.SetDPI(TrafficBackground.GetDPI()+.1),this.Countdown2Disable--,0>this.Countdown2Disable&&(a.ctx.fillStyle=Settings.BackDrawer.Background,a.ctx.fillRect(0,0,a.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),a.S(Settings.Game.Hcell*
(Settings.Game.Hcount+1))),this.Enabled=!1)):console.log((b<<0)+"FPS--"),this.BeforeOpe=1):b>Settings.Background.FPS[1]?(-1==this.BeforeOpe?(console.log((b<<0)+"FPS++ => DPIfactor: "+(10*(TrafficBackground.GetDPI()-.1)<<0)),TrafficBackground.SetDPI(TrafficBackground.GetDPI()-.1)):console.log((b<<0)+"FPS++"),this.BeforeOpe=-1):this.BeforeOpe=0;this.FPSspan=this.FPScount=0}TrafficBackground.Tick()};var BackDrawer=function(){this.Name="Back";this.Enabled=!0};
BackDrawer.prototype.Draw=function(a,c){a.ctx.clearRect(0,0,a.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),a.S(Settings.Game.Hcell*(Settings.Game.Hcount+1)));a.ctx.fillStyle=Settings.BackDrawer.Background;a.ctx.strokeStyle=Settings.BackDrawer.Border;a.ctx.save();a.ctx.globalAlpha=Settings.BackDrawer.Alpha;a.ctx.fillRect(0,0,a.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),a.S(Settings.Game.Hcell*(Settings.Game.Hcount+1)));a.ctx.restore();for(var b=1;b<Settings.Game.Wcount;b++)a.Line(b*Settings.Game.Wcell-
1,1*Settings.Game.Hcell,b*Settings.Game.Wcell-1,30*Settings.Game.Hcell);a.ctx.fillStyle=Settings.BackDrawer.TextColor;a.ctx.font=(a.S(Settings.Game.Hcell-4)<<0)+"px "+Settings.Game.FontName;a.TextLeft("Life:  "+Game.life.toString(),Settings.BackDrawer.MarginLeft*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-2+.5),Settings.Game.Wcell*Settings.Game.Wcount/2);a.TextLeft("Score: "+Game.score.toString(),Settings.BackDrawer.MarginLeft*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-
1+.5),Settings.Game.Wcell*Settings.Game.Wcount/2);a.TextRight("Hint: "+Game.hintCount.toString(),(Settings.Game.Wcount-Settings.BackDrawer.MarginRight)*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-1+.5),Settings.Game.Wcell*Settings.Game.Wcount/2);a.TextRight("Lv."+Game.GetLevelText(),(Settings.Game.Wcount-Settings.BackDrawer.MarginRight)*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-2+.5),Settings.Game.Wcell*Settings.Game.Wcount/2)};
var Dropper=function(){this.Name="Dropper";this.Enabled=!0;this.dx=Settings.Dropper.MoveSpeed;this.x=(Settings.Game.Wcount-1)/2<<0};
Dropper.prototype.BeforeDraw=function(a,c){var b=this;this.dx=Math.sign(this.dx)*Math.min(Settings.Dropper.MaxSpeed,Settings.Dropper.MoveSpeed+(Math.max(Game.level/Settings.NumNodes.LevelToMaxWeighting,Settings.Dropper.SpeedUpLevel)-Settings.Dropper.SpeedUpLevel)/Settings.Dropper.SpeedUpSpeed);if(this.x<<0!=this.x+this.dx*c/1E3<<0&&(this.x+=this.dx*c/1E3,Math.random()<Settings.Dropper.TurnProbability&&(this.dx*=-1),Math.random()<Settings.Dropper.DropProbability)){var d=a.find(function(a){return"NumNodes"==
a.Name});if(d instanceof NumNodes)d.nums.some(function(a){return a[0]==Math.round(b.x+Settings.Game.Wcount)%Settings.Game.Wcount&&1>a[1]})||d.Add(Math.round(this.x+Settings.Game.Wcount)%Settings.Game.Wcount,0);else throw"ERROR";}};
Dropper.prototype.Draw=function(a,c){this.x+=this.dx*c/1E3;this.x=(this.x+Settings.Game.Wcount)%Settings.Game.Wcount;a.ctx.fillStyle=Settings.Dropper.Color;a.ctx.beginPath();a.RoundedRect(this.x*Settings.Game.Wcell,0,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell);a.ctx.fill();this.x>Settings.Game.Wcount-1&&(a.ctx.beginPath(),a.RoundedRect((this.x-Settings.Game.Wcount)*Settings.Game.Wcell,0,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell),a.ctx.fill())};
var Shooter=function(){this.Name="Shooter";this.Enabled=!0;this.Keymap=Settings.Shotter.Keymap;this.KeySleepMax1=Settings.Shotter.KeySleepMax1;this.KeySleepMax2=Settings.Shotter.KeySleepMax2;this.KeyMode=[0,0,0,0];this.dx=0;this.x=(Settings.Game.Wcount-1)/2<<0;this.y=Settings.Shotter.Y;this.BlinkCount=0};
Shooter.prototype.Init=function(a){function c(b){for(var f=d.KeyMode.map(function(){return 0}),c=0;c<b.length;c++){var e=b[c].pageY-a.offsetTop,k=a.clientHeight;e<k/3?f[2]=1:e<k/3*2?f[3]=1:b[c].pageX-a.offsetLeft<a.clientWidth/2?f[0]=1:f[1]=1}for(b=0;b<f.length;b++)0==d.KeyMode[b]!=(0==f[b])&&(d.KeyMode[b]=f[b])}function b(){d.KeyMode=d.KeyMode.fill(0)}var d=this;document.addEventListener("keydown",function(a){if(!a.repeat){var b=d.Keymap.findIndex(function(b){return b==a.keyCode});0>b||(a.preventDefault(),
d.KeyMode[b]=1)}});document.addEventListener("keyup",function(a){var b=d.Keymap.findIndex(function(b){return b==a.keyCode});0>b||(a.preventDefault(),d.KeyMode[b]=0)});a.addEventListener("touchstart",function(a){return c(a.touches)});a.addEventListener("touchmove",function(a){return c(a.touches)});a.addEventListener("touchend",function(a){return c(a.touches)});a.addEventListener("touchcancel",b);window.addEventListener("blur",b);return this};
Shooter.prototype.BeforeDraw=function(a,c){var b=this;this.KeyMode.forEach(function(c,e){if(0!=c&&(1==c||0==(c-b.KeySleepMax1[e])%b.KeySleepMax2[e]&&c>=b.KeySleepMax1[e]))switch(e){case 0:b.dx=-Settings.Shotter.MoveSpeed;break;case 1:b.dx=Settings.Shotter.MoveSpeed;break;case 2:a.find(function(a){return"Shots"==a.Name}).Add(Math.round(b.x+Settings.Game.Wcount)%Settings.Game.Wcount,b.y);break;case 3:a.find(function(a){return"NumNodes"==a.Name}).Hint()}},this);this.KeyMode=this.KeyMode.map(function(a){return 0==
a?0:a+1})};
Shooter.prototype.Draw=function(a,c){function b(){a.ctx.beginPath();a.ctx.moveTo(a.S((this.x+.5)*Settings.Game.Wcell-.5),a.S(this.y*Settings.Game.Hcell));a.ctx.lineTo(a.S((this.x+.5-.3)*Settings.Game.Wcell-.5),a.S((this.y+1)*Settings.Game.Hcell));a.ctx.lineTo(a.S((this.x+.5+.3)*Settings.Game.Wcell-.5),a.S((this.y+1)*Settings.Game.Hcell));a.ctx.fill()}0<this.dx&&this.x<<0!=this.x+this.dx<<0?(this.x=this.x+this.dx<<0,this.dx=0):0>this.dx&&Math.ceil(this.x)!=Math.ceil(this.x+this.dx)&&(this.x=Math.ceil(this.x+
this.dx),this.dx=0);0!=this.dx&&(this.x+=this.dx);this.x=(this.x+Settings.Game.Wcount)%Settings.Game.Wcount;a.ctx.save();this.BlinkCount=(this.BlinkCount+1)%Settings.Shotter.Beam.BlinkSpeed;a.ctx.globalAlpha=Math.sin(this.BlinkCount/Settings.Shotter.Beam.BlinkSpeed*Math.PI*2)/4+.5;a.ctx.strokeStyle=Settings.Shotter.Beam.Color;a.Line((this.x+.5)*Settings.Game.Wcell-1,1*Settings.Game.Hcell,(this.x+.5)*Settings.Game.Wcell-1,this.y*Settings.Game.Hcell);a.ctx.stroke();a.ctx.restore();a.ctx.fillStyle=Settings.Shotter.Color;
b.apply(this);this.x>Settings.Game.Wcount-1&&(this.x-=Settings.Game.Wcount,b.apply(this),this.x+=Settings.Game.Wcount)};var Shots=function(){this.Name="Shots";this.Enabled=!0;this.shots=[]};Shots.prototype.Add=function(a,c){this.shots.push([a,c])};Shots.prototype.Clear=function(){this.shots=[]};
Shots.prototype.Draw=function(a,c){a.ctx.fillStyle=Settings.Shots.Color;a.ctx.save();a.Shadow();a.ctx.beginPath();this.shots.forEach(function(b){b[1]-=Settings.Shots.MoveSpeed;a.Round((b[0]+.5)*Settings.Game.Wcell-.5,b[1]*Settings.Game.Hcell,Settings.Shots.Radius*Settings.Game.Hcell);a.ctx.closePath()});a.ctx.fill();a.ctx.restore()};Shots.prototype.AfterDraw=function(a,c){this.shots=this.shots.filter(function(a){return 0<a[1]})};
var NumNodes=function(){this.Name="NumNodes";this.Enabled=!0;this.nums=[]};NumNodes.prototype.Add=function(a,c,b){if(!b)for(;;){for(var d=b=Math.max(2,Math.random()*(Settings.NumNodes.minNumber+Game.level/Settings.NumNodes.LevelToMaxWeighting)<<0),e=0;e<Settings.NumNodes.MaxFactCount;e++){d=Factorization(d);if(0==d[0])break;d=d[1]}if(e!=Settings.NumNodes.MaxFactCount)break}this.nums.push([a,c,b?b:Math.max(2,Math.random()*Game.level/Settings.NumNodes.LevelToMaxWeighting<<0),0])};
NumNodes.prototype.Hint=function(){0>=Game.hintCount||(Game.hintCount--,this.nums.forEach(function(a){0==Factorization(a[2])[0]?a[3]=1:a[3]=2}))};
NumNodes.prototype.Draw=function(a,c){this.nums.forEach(function(a){return a[1]+=Settings.NumNodes.MoveSpeed});a.ctx.save();a.Shadow();for(var b={tmp:0};b.tmp<Settings.NumNodes.Colors.length;b={tmp:b.tmp},b.tmp++)a.ctx.fillStyle=Settings.NumNodes.Colors[b.tmp],a.ctx.beginPath(),this.nums.forEach(function(b){return function(c){c[3]==b.tmp&&(a.RoundedRect(c[0]*Settings.Game.Wcell,c[1]*Settings.Game.Hcell,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell),a.ctx.closePath())}}(b)),a.ctx.fill();
a.ctx.restore();a.ctx.fillStyle=Settings.NumNodes.TextColor;a.ctx.font=(a.S(Settings.Game.Hcell-4)<<0)+"px "+Settings.Game.FontName;this.nums.forEach(function(b){a.TextCenter(b[2].toString(),(b[0]+.5)*Settings.Game.Wcell,(b[1]+.5)*Settings.Game.Hcell,Settings.Game.Wcell-4)})};
NumNodes.prototype.AfterDraw=function(a,c){this.nums=this.nums.filter(function(b){if(b[1]<=Settings.Game.Hcount-3)return!0;Settings.ScoreAndLevel(1,b[2]);0!=Factorization(b[2])[0]&&a.find(function(a){return"AfterImages"==a.Name}).Add(b[0],b[1],b[2]);return!1})};var AfterImages=function(){this.Name="AfterImages";this.Enabled=!0;this.nums=[]};AfterImages.prototype.Add=function(a,c,b){this.nums.push([a,c,b,Settings.AfterImages.ShowTicks])};
AfterImages.prototype.Draw=function(a,c){this.nums.forEach(function(a){return--a[3]});a.ctx.save();a.ctx.globalCompositeOperation="lighter";a.ctx.fillStyle=Settings.AfterImages.Back;this.nums.forEach(function(b){a.ctx.globalAlpha=b[3]/Settings.AfterImages.ShowTicks*Settings.AfterImages.MaxAlpha;a.RoundedRect(b[0]*Settings.Game.Wcell,b[1]*Settings.Game.Hcell,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell);a.ctx.closePath();a.ctx.fill()});a.ctx.fillStyle=Settings.AfterImages.Fore;a.ctx.font=
(a.S(Settings.Game.Hcell-4)<<0)+"px "+Settings.Game.FontName;this.nums.forEach(function(b){a.ctx.globalAlpha=b[3]/Settings.AfterImages.ShowTicks*Settings.AfterImages.MaxAlpha;a.TextCenter(b[2].toString(),(b[0]+.5)*Settings.Game.Wcell,(b[1]+.5)*Settings.Game.Hcell,Settings.Game.Wcell-4)});a.ctx.restore()};AfterImages.prototype.AfterDraw=function(a,c){this.nums=this.nums.filter(function(a){return 0<a[3]})};var Filters=function(){this.Name="Filters";this.Enabled=!0;this.filters=[]};
Filters.prototype.Add=function(a){this.filters.push(a)};Filters.prototype.Draw=function(a,c){a.ctx.strokeStyle=Settings.Filters.Color;a.ctx.save();a.Shadow();a.ctx.beginPath();this.filters.forEach(function(b){a.ctx.moveTo(0,a.S(Settings.Game.Hcell*b));a.ctx.lineTo(a.S(Settings.Game.Wcell*Settings.Game.Wcount),a.S(Settings.Game.Hcell*b))});a.ctx.stroke();a.ctx.restore()};var ButtonNodes=function(){this.Name="ButtonNodes";this.Enabled=!0;this.texts=[]};
ButtonNodes.prototype.Add=function(a,c,b,d,e,f,g){this.texts.push({x:a,y:c,w:b,h:d,text:e,fontsize:f,fn:g})};ButtonNodes.prototype.Clear=function(){this.texts=[]};
ButtonNodes.prototype.Draw=function(a,c){a.ctx.fillStyle=Settings.ButtonNodes.Color;a.ctx.save();a.Shadow();a.ctx.beginPath();this.texts.forEach(function(b){a.RoundedRect(b.x*Settings.Game.Wcell,b.y*Settings.Game.Hcell,b.w*Settings.Game.Wcell,b.h*Settings.Game.Hcell,Settings.Game.Rcell);a.ctx.closePath()});a.ctx.fill();a.ctx.restore();a.ctx.fillStyle=Settings.ButtonNodes.TextColor;this.texts.forEach(function(b){a.ctx.font=(a.S(Settings.Game.Hcell*b.fontsize-4)<<0)+"px "+Settings.Game.FontName;a.TextCenter(b.text,
(b.x+b.w/2)*Settings.Game.Wcell,(b.y+b.h/2)*Settings.Game.Hcell,Settings.Game.Wcell*b.w-4)})};var Fading=function(){this.Name="Fading";this.Enabled=!0;this.Finished=!1;this.CurrentBrightness=0};
Fading.prototype.Draw=function(a,c){this.CurrentBrightness>Settings.Fading.Speed?(a.ctx.fillStyle=Settings.Fading.Color,a.ctx.globalAlpha=1-this.CurrentBrightness,a.ctx.fillRect(0,0,a.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),a.S(Settings.Game.Hcell*(Settings.Game.Hcount+1))),this.CurrentBrightness++):this.Finished=!0};
function OnhitNumShots(a,c,b){b=[];for(var d=[],e=0;e<c.shots.length&&!(0<=d.indexOf(e));e++)for(var f=0;f<a.nums.length&&!(0<=b.indexOf(f));f++)a.nums[f][0]==c.shots[e][0]&&Math.abs(a.nums[f][1]-c.shots[e][1])<.5+Settings.Shots.Radius&&(b.push(f),d.push(e));for(;0<d.length;)c.shots.splice(d.pop(),1);for(;0<b.length;)c=b.pop(),d=Factorization(a.nums[c][2]),Settings.ScoreAndLevel(2,a.nums[c][2]),0!=d[0]?(a.Add((a.nums[c][0]+Settings.Game.Wcount-1)%Settings.Game.Wcount,a.nums[c][1]-1,d[0]),a.Add((a.nums[c][0]+
Settings.Game.Wcount+1)%Settings.Game.Wcount,a.nums[c][1]-1,d[1])):Game.Elms.find(function(a){return"AfterImages"==a.Name}).Add(a.nums[c][0],a.nums[c][1],a.nums[c][2]),a.nums.splice(c,1)}
function OnhitNumNum(a,c,b){var d=[];for(c=0;c<a.nums.length&&!(0<=d.indexOf(c));c++)for(b=c+1;b<a.nums.length&&!(0<=d.indexOf(b));b++)a.nums[c][0]==a.nums[b][0]&&1>Math.abs(a.nums[c][1]-a.nums[b][1])&&(d.push(c),d.push(b));if(0!=d.length){for(c=0;c<d.length;c+=2)a.Add(a.nums[d[c]][0],(a.nums[d[c]][1]+a.nums[d[c+1]][1])/2,a.nums[d[c]][2]+a.nums[d[c+1]][2]);a.nums=a.nums.filter(function(a,b){return 0>d.indexOf(b)})}}
function OnhitFiltersNum(a,c,b){b=[];for(var d=0;d<a.filters.length;d++)for(var e=0;e<c.nums.length&&!(0<=b.indexOf(e));e++).5>Math.abs(c.nums[e][1]-a.filters[d]+.5)&&0==Factorization(c.nums[e][2])[0]&&b.push(e);for(b.sort(function(a,b){return a-b});0<b.length;)a=b.pop(),Settings.ScoreAndLevel(0,c.nums[a][2]),c.nums.splice(a,1)}
function OnhitBtnShots(a,c,b){b=[];for(var d=[],e=0;e<c.shots.length&&!(0<=d.indexOf(e));e++)for(var f=0;f<a.texts.length&&!(0<=b.indexOf(f));f++)a.texts[f].y-Settings.Shots.Radius<=c.shots[e][1]&&a.texts[f].y+a.texts[f].h+Settings.Shots.Radius>=c.shots[e][1]&&a.texts[f].x<=c.shots[e][0]&&a.texts[f].x+a.texts[f].w-1>=c.shots[e][0]&&(b.push(f),d.push(e));for(;0<d.length;)c.shots.splice(d.pop(),1);for(;0<b.length;)c=b.pop(),a.texts[c].fn()}
function onLoad(a){a.find(function(a){return"Fading"==a.Name}).Enabled=!1;a.find(function(a){return"Dropper"==a.Name}).Enabled=!1;a.find(function(a){return"NumNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Filters"==a.Name}).Enabled=!1;var c=a.find(function(a){return"ButtonNodes"==a.Name});if(c instanceof ButtonNodes)c.Add(1,1,Settings.Game.Wcount-2,3,"Prime Shooter",2,function(){return c.texts[0].text="Prime Shooter"==c.texts[0].text?"\u7d20\u6570\u30b7\u30e5\u30fc\u30c6\u30a3\u30f3\u30b0":
"Prime Shooter"}),c.Add(1,11,3,2,"Start",1.5,function(){a.find(function(a){return"Dropper"==a.Name}).Enabled=!0;a.find(function(a){return"NumNodes"==a.Name}).Enabled=!0;a.find(function(a){return"Filters"==a.Name}).Enabled=!0;a.find(function(a){return"ButtonNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Shots"==a.Name}).Clear();AddFilter(a)}),c.Add(Settings.Game.Wcount-4,11,3,2,"Help",1.5,function(){document.getElementById("help").classList.toggle("hide")});else throw"ERROR";}
function onTick(a,c){var b=Settings.onTick.HintperLevel*Settings.NumNodes.LevelToMaxWeighting,d=Settings.onTick.FilterperLevel*Settings.NumNodes.LevelToMaxWeighting;Game.level>Game.maxLevel&&(Game.level/b<<0>Game.maxLevel/b<<0&&Game.hintCount++,Game.level/d<<0>Game.maxLevel/d<<0&&AddFilter(a),Game.maxLevel=Game.level);if(0>=Game.life)if(!a.find(function(a){return"Fading"==a.Name}).Finished)a.find(function(a){return"Fading"==a.Name}).Enabled||(Game.life=0,a.find(function(a){return"Dropper"==a.Name}).Enabled=
!1,a.find(function(a){return"NumNodes"==a.Name}).Enabled=!1,a.find(function(a){return"Filters"==a.Name}).Enabled=!1,a.find(function(a){return"Fading"==a.Name}).Enabled=!0);else if(a.find(function(a){return"Fading"==a.Name}).Enabled){a.find(function(a){return"Shots"==a.Name}).shots=[];a.find(function(a){return"Fading"==a.Name}).Enabled=!1;var e=a.find(function(a){return"ButtonNodes"==a.Name});if(e instanceof ButtonNodes)e.Enabled=!0,e.Clear(),e.Add(1,1,Settings.Game.Wcount-2,3,"Gameover",2,function(){return!0}),
e.Add(2,5,Settings.Game.Wcount-4,1,"Score: "+Game.score+"pt",1,function(){return 0}),e.Add(2,6.5,Settings.Game.Wcount-4,1,"Rank: ...",1,function(){return 0}),e.Add(1.5,11,Settings.Game.Wcount-3,2,"Add to Ranking",1.5,function(){if(e instanceof ButtonNodes&&"Add to Ranking"==e.texts[e.texts.length-1].text){var a=prompt("Enter your name...","anonymous");if(a&&0<a.length){var b=function(){c++;e instanceof ButtonNodes&&2==c&&(e.texts[e.texts.length-1].text="Finish!")};e.texts[e.texts.length-1].text="...";
var c=0;MyStorage.Add(1,JSON.stringify({Score:Game.score,Level:Game.level,Name:a}),b);MyStorage.Add(2,JSON.stringify({Date:DateFormat(new Date),IP:IPAddress,UA:window.navigator.userAgent}),b)}}}),MyStorage.Get(1,function(a){a=a.map(function(a){return JSON.parse(a)});a=a.sort(function(a,b){return b.Score-a.Score});var b=document.getElementById("rankingList");b.innerHTML="";a.forEach(function(a,c){b.innerHTML+="<li><div>#"+(c+1)+"</div><div>"+a.Score+"pt</div><div>Lv."+Game.GetLevelText(a.Level)+"</div><div>"+
a.Name+"</div></li>"});var c=a.findIndex(function(a){return a.Score<=Game.score})+1;0==c&&(c=a.length+1);e.texts[2].text="Rank: "+c+"/"+(a.length+1);document.getElementById("ranking").classList.remove("hide")});else throw"ERROR";}}
function AddFilter(a){var c=a.find(function(a){return"Shots"==a.Name}).shots,b=a.find(function(a){return"Shooter"==a.Name}).x;a.find(function(a){return"Dropper"==a.Name}).Enabled=!1;a.find(function(a){return"NumNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Shooter"==a.Name}).Enabled=!1;setTimeout(function(){return a.find(function(a){return"Shooter"==a.Name}).Enabled=!0},1E3);a.find(function(a){return"Shooter"==a.Name}).KeyMode=a.find(function(a){return"Shooter"==a.Name}).KeyMode.fill(0);a.find(function(a){return"Shooter"==
a.Name}).x=2;var d=a.find(function(a){return"Filters"==a.Name});d instanceof Filters&&d.Add(5);var e=a.find(function(a){return"ButtonNodes"==a.Name});if(e instanceof ButtonNodes)e.Enabled=!0,e.Clear(),e.Add(1,1,Settings.Game.Wcount-2,3,"Add Filter",2,function(){return e.texts[0].text="Add Filter"==e.texts[0].text?"13\u3063\u3066\u3044\u3044\u3088\u306d\uff01":"Add Filter"}),e.Add(1,Settings.Game.Hcount-9,1,2,"\u2191",1.5,function(){var b=a.find(function(a){return"Filters"==a.Name});b instanceof Filters&&
(b.filters[b.filters.length-1]=Math.min(Settings.Game.Hcount-5,Math.max(1,b.filters[b.filters.length-1]-1)))}),e.Add(2,Settings.Game.Hcount-9,1,2,"\u2193",1.5,function(){var b=a.find(function(a){return"Filters"==a.Name});b instanceof Filters&&(b.filters[b.filters.length-1]=Math.min(Settings.Game.Hcount-5,Math.max(1,b.filters[b.filters.length-1]+1)))}),e.Add(3,Settings.Game.Hcount-9,Settings.Game.Wcount-4,2,"Add & Start",1.5,function(){a.find(function(a){return"Dropper"==a.Name}).Enabled=!0;a.find(function(a){return"NumNodes"==
a.Name}).Enabled=!0;a.find(function(a){return"ButtonNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Shots"==a.Name}).shots=c;a.find(function(a){return"Shooter"==a.Name}).x=b});else throw"ERROR";}var Game;
(function(a){a.score=0;a.level=1;a.maxLevel=0;a.life=Settings.Game.life;a.hintCount=0;var c;a.Elms=[(new Background).Init("bg"),new BackDrawer,new Dropper,,new Shots,new NumNodes,new Filters,new AfterImages,new ButtonNodes,new Fading];var b=[{Fn:OnhitBtnShots,Elm1:"ButtonNodes",Elm2:"Shots"},{Fn:OnhitNumShots,Elm1:"NumNodes",Elm2:"Shots"},{Fn:OnhitNumNum,Elm1:"NumNodes",Elm2:"NumNodes"},{Fn:OnhitFiltersNum,Elm1:"Filters",Elm2:"NumNodes"}];a.Init=function(){c=new ResizingCanvas(document.getElementById("c1"),
document.documentElement,Settings.Game.Wcell*Settings.Game.Wcount,Settings.Game.Hcell*Settings.Game.Hcount);a.Elms[3]=(new Shooter).Init(c.ctx.canvas);onLoad(a.Elms)};var d=void 0;a.Tick=function(e){void 0===d&&(d=e);a.Elms.forEach(function(b){"BeforeDraw"in b&&b.Enabled&&b.BeforeDraw(a.Elms,e-d)});a.Elms.forEach(function(a){"Draw"in a&&a.Enabled&&a.Draw(c,e-d)});a.Elms.forEach(function(b){"AfterDraw"in b&&b.Enabled&&b.AfterDraw(a.Elms,e-d)});b.forEach(function(b){var c=a.Elms.find(function(a){return a.Name==
b.Elm1});if(!c)throw"undefined node name";var f=a.Elms.find(function(a){return a.Name==b.Elm2});if(!f)throw"undefined node name";c.Enabled&&f.Enabled&&b.Fn(c,f,e-d)});d=e;onTick(a.Elms,e-d)};a.GetLevelText=function(b){b=void 0===b?a.level:b;return 0==b%Settings.NumNodes.LevelToMaxWeighting?b.toString():b<Settings.NumNodes.LevelToMaxWeighting?b+"/"+Settings.NumNodes.LevelToMaxWeighting:(b/Settings.NumNodes.LevelToMaxWeighting<<0)+"+"+b%Settings.NumNodes.LevelToMaxWeighting+"/"+Settings.NumNodes.LevelToMaxWeighting}})(Game||
(Game={}));function LoadScript(a){var c=document.createElement("script");c.src=a;document.body.appendChild(c)}function DateFormat(a){var c=a.getFullYear(),b=a.getMonth()+1,d=a.getDate(),e=a.getHours(),f=a.getMinutes();a=a.getSeconds();return c+"/"+b+"/"+d+" "+e+":"+f+":"+a}var IPAddress="",AccessTime="";function AddAccessLog(a){IPAddress=a.ip;MyStorage.Add(4,AccessTime+" "+IPAddress+" "+window.navigator.userAgent,function(){return 0})}var MyStorage;
(function(a){function c(a){return"https://script.google.com/macros/s/AKfycbwgY_buxMtX3TLIxYrNfpyFZhyewRU0A3TnvDCi4A5yyY20AT0/exec?type=Get&ID="+a.toString()}function b(a,b){return"https://script.google.com/macros/s/AKfycbwgY_buxMtX3TLIxYrNfpyFZhyewRU0A3TnvDCi4A5yyY20AT0/exec?type=Add&ID="+a.toString()+"&Text="+encodeURIComponent(b)}a.GettingURL=c;a.AddingURL=b;a.Get=function(b,e){a._GetCB=e;LoadScript(c(b)+("&prefix="+encodeURIComponent("MyStorage._GetCB")))};a.Add=function(c,e,f){a._AddCB=f;LoadScript(b(c,
e)+("&prefix="+encodeURIComponent("MyStorage._AddCB")))}})(MyStorage||(MyStorage={}));Polyfill.Do();window.addEventListener("load",function(){function a(){Game.Tick(GetTime());requestAnimationFrame(a)}AccessTime=DateFormat(new Date);LoadScript(MyStorage.AddingURL(3,AccessTime+" "+window.navigator.userAgent)+"&prefix="+encodeURIComponent(""));LoadScript("https://api.ipify.org?format=jsonp&callback=AddAccessLog");Game.Init();a()});document.body.removeChild(document.getElementById("message"));