// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// ==/ClosureCompiler==
var Colors={Back:"#000",Border:"#222",UI:"#777",Beam:"#F00",Text:"#CCC",Node:["#333","#242","#422"],AfterImageFore:"#FF0",AfterImageBack:"#800",Filter:"#5F2",Shooter:"#888",Dropper:"#555",Shot:"#CCC",ShadowX:0,ShadowY:3,ShadowR:5},Settings={BackDrawer:{Background:Colors.Back,Alpha:.8,Border:Colors.Border,TextColor:Colors.UI,MarginLeft:.5,MarginRight:.5},Background:{FPSspan:10,FPS:[50,65],DisableCount:10},Dropper:{MoveSpeed:4,SpeedUpLevel:300,SpeedUpSpeed:31,MaxSpeed:9,TurnProbability:.4,DropProbability:.2,
Color:Colors.Dropper},Shotter:{Beam:{BlinkSpeed:100,Color:Colors.Beam},Y:28,MoveSpeed:.5,Color:Colors.Shooter,Keymap:[37,39,38,72],KeySleepMax1:[9,9,21,Infinity],KeySleepMax2:[3,3,9,Infinity]},Shots:{Radius:.2,Color:Colors.Shot,MoveSpeed:.5},NumNodes:{LevelToMaxWeighting:7,Colors:Colors.Node,MaxFactCount:6,MoveSpeed:.02,TextColor:Colors.Text,minNumber:10},AfterImages:{ShowTicks:100,MaxAlpha:.7,Fore:Colors.AfterImageFore,Back:Colors.AfterImageBack},Filters:{Color:Colors.Filter},ButtonNodes:{Color:Colors.Node[0],
TextColor:Colors.Text},Fading:{Speed:100,Color:Colors.Back},onTick:{HintperLevel:13,FilterperLevel:97},Game:{Wcount:9,Hcount:32,Wcell:34,Hcell:20,Rcell:5,FontName:'"Kokoro", "Rounded Mplus 1c", "Open Sans", "Noto Sans Japanese", "Yu Gothic", "Meiryo UI", sans-serif',life:5},ResizingCanvas:{Margin:10,shadowBlur:Colors.ShadowR,shadowColor:"#000",shadowOffsetX:Colors.ShadowX,shadowOffsetY:Colors.ShadowY},ScoreAndLevel:function(a,b){var e=0==Factorization(b)[0];switch(a){case 0:Game.score+=7*b;Game.level+=
7;break;case 1:e?(Game.score+=11*b,Game.level+=11):(Game.score-=17*b,Game.level-=17,Game.life--);break;case 2:e?(Game.score-=31*b,Game.level-=31,Game.life-=3):(Game.score+=b,Game.level++)}}},Polyfill;
(function(a){a.Do=function(){var b=void 0,a=function(a){"number"==typeof b&&clearTimeout(b);b=setTimeout(a,1E3/60)};window.requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||a;Array.prototype.find||Object.defineProperty(Array.prototype,"find",{value:function(b,a){for(var f=Object(this),d=f.length>>>0,c=0;c<d;){var e=f[c];if(b.call(a,e,c,f))return e;c++}}});Array.prototype.findIndex||Object.defineProperty(Array.prototype,"findIndex",{value:function(b,a){for(var f=
Object(this),d=f.length>>>0,c=0;c<d;){if(b.call(a,f[c],c,f))return c;c++}return-1}});Array.prototype.fill||Object.defineProperty(Array.prototype,"fill",{value:function(b,a,f){var d=Object(this),c=d.length>>>0;a>>=0;a=0>a?Math.max(c+a,0):Math.min(a,c);f=void 0===f?c:f>>0;for(c=0>f?Math.max(c+f,0):Math.min(f,c);a<c;)d[a]=b,a++;return d}});Math.sign=Math.sign||function(b){return 0===b?0:0<b?1:-1}}})(Polyfill||(Polyfill={}));
function GetTime(){var a=window.performance&&performance.now;return a&&a.call(performance)||(new Date).getTime()}function Factorization(a){if(0==a%2&&2!=a)return[2,a/2];for(var b=3;b<a;b+=2)if(0===a%b)return[b,a/b];return[0,a]}var TrafficBackground;
(function(a){function b(b,a){return Math.random()*(a-b)+b}var e="c1",d=[.7,1],c=[3,2],f=1,g=function(){function b(b,a){var f=this;this.Parent=a;if(b.getContext)this.ctx=b.getContext("2d");else throw"Canvas\u304c\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u3088\u3046\u3067\u3059\u3002Chrome\u3084Chrome\u306a\u3069\u306e\u30ca\u30a6\u3044\u30d6\u30e9\u30a6\u30b6\u30fc\u3092\u4f7f\u3044\u306a\u3055\u3044";var d=this;(function(b){var a=!1;window.addEventListener("resize",function(){"number"==typeof a&&
clearTimeout(a);a=setTimeout(b,100)})})(function(){return f.OnResize.call(d)});this.scaleY=this.scaleX=1;this.OnResize()}b.prototype.OnResize=function(){var b=this.ctx.canvas;this.scaleX=this.Parent.clientWidth;this.scaleY=this.Parent.clientHeight;b.style.width=this.scaleX+"px";b.style.height=this.scaleY+"px";this.scaleX*=(window.devicePixelRatio||1)/f;this.scaleY*=(window.devicePixelRatio||1)/f;b.width=this.scaleX;b.height=this.scaleY;this.ctx.lineWidth=(window.devicePixelRatio||1)/f*1};b.prototype.Sx=
function(b){return b*this.scaleX};b.prototype.Sy=function(b){return b*this.scaleY};b.prototype.Line=function(b,a,f,d){this.ctx.beginPath();this.ctx.moveTo(this.Sx(b),this.Sy(a));this.ctx.lineTo(this.Sx(f),this.Sy(d));this.ctx.stroke()};return b}(),k=function(){function a(){this.Name="Dots";this.Enabled=!0;this.cities=[];this.cars=[]}a.prototype.Init=function(a){a.ctx.globalCompositeOperation="source-over";a.ctx.fillStyle="#000";a.ctx.fillRect(0,0,a.Sx(1),a.Sy(1));for(var f=0;50>f;f++){var e=b(d[0],
d[1]),g=b(0,2*Math.PI);this.cities.push({x:Math.random(),y:Math.random(),dx:e*Math.cos(g),dy:e*Math.sin(g),hue:12*Math.random()<<0})}for(f=0;500>f;f++)e=b(0,50)<<0,g=this.GetNeightbor(a,this.cities[e].x,this.cities[e].y,b(1,4)<<0),this.cars.push({x:this.cities[e].x,y:this.cities[e].y,speed:b(c[0],c[1]),hue:this.cities[e].hue,to:g});return this};a.prototype.Draw=function(a,d){for(var c=0;c<this.cities.length;c++){var e=this.cities[c];e.x+=e.dx/a.Sx(1)/f;e.y+=e.dy/a.Sy(1)/f;1<e.x?(e.dx=-e.dx,e.hue+=
1):0>e.x&&(e.dx=-e.dx,e.hue+=1);1<e.y?(e.dy=-e.dy,e.hue+=1):0>e.y&&(e.dy=-e.dy,e.hue+=1);e.hue%=12}a.ctx.globalAlpha=.1;a.ctx.globalCompositeOperation="source-over";a.ctx.fillStyle="#000";a.ctx.fillRect(0,0,a.Sx(1),a.Sy(1));a.ctx.globalAlpha=.3;a.ctx.globalCompositeOperation="lighter";for(e=0;12>e;e++){a.ctx.strokeStyle="hsl("+30*e+", 80%,70%)";a.ctx.beginPath();for(c=0;c<this.cars.length;c++){var g=this.cars[c];if(g.hue==e)if(Math.pow(a.Sx(g.x-this.cities[g.to].x),2)+Math.pow(a.Sy(g.y-this.cities[g.to].y),
2)<Math.pow(g.speed/f,2)){a.ctx.moveTo(a.Sx(g.x)<<0,a.Sy(g.y)<<0);a.ctx.lineTo(a.Sx(this.cities[g.to].x)<<0,a.Sy(this.cities[g.to].y)<<0);this.cities[g.to].hue=(this.cities[g.to].hue+(.01>Math.random()?1:0))%12;var h=this.GetNeightbor(a,this.cities[g.to].x,this.cities[g.to].y,b(1,4)<<0);this.cars[c]={x:this.cities[g.to].x,y:this.cities[g.to].y,speed:g.speed,hue:this.cities[g.to].hue,to:h}}else{var h=[this.cities[g.to].x-g.x,this.cities[g.to].y-g.y],k=Math.sqrt(Math.pow(a.Sx(h[0]),2)+Math.pow(a.Sy(h[1]),
2))*f;h[0]*=g.speed/k;h[1]*=g.speed/k;a.ctx.moveTo(a.Sx(g.x)<<0,a.Sy(g.y)<<0);a.ctx.lineTo(a.Sx(g.x+h[0])<<0,a.Sy(g.y+h[1])<<0);this.cars[c].x+=h[0];this.cars[c].y+=h[1]}}a.ctx.stroke()}};a.prototype.GetNeightbor=function(b,a,f,d){for(var e=Array(this.cities.length),c=0;c<this.cities.length;c++)e[c]=Math.sqrt(Math.pow(b.Sx(this.cities[c].x-a),2)+Math.pow(b.Sy(this.cities[c].y-f),2));b=new Set;a=Infinity;for(var g=f=0;g<=d;g++){for(c=0;c<e.length;c++)!b.has(c)&&a>e[c]&&(a=e[c],f=c);b.add(f);a=Infinity}return f};
return a}(),h;(function(b){b.Init=function(){b.c1=new g(document.getElementById(e),document.documentElement);b.Elm=(new k).Init(b.c1)};var a=void 0,f=0;b.Tick=function(d){-1<f++&&(f=0,void 0===a&&(a=d),b.Elm.Draw(b.c1,d-a),a=d)}})(h||(h={}));a.Init=function(b){e=b;h.Init()};a.Tick=function(){h.Tick(GetTime())};a.GetDPI=function(){return f};a.SetDPI=function(b){f=b;h.c1.OnResize()}})(TrafficBackground||(TrafficBackground={}));
var ResizingCanvas=function(){function a(b,a,d,c){var f=this;this.Parent=a;if(b.getContext)this.ctx=b.getContext("2d");else throw"Canvas\u304c\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u3088\u3046\u3067\u3059\u3002Chrome\u3084Chrome\u306a\u3069\u306e\u30ca\u30a6\u3044\u30d6\u30e9\u30a6\u30b6\u30fc\u3092\u4f7f\u3044\u306a\u3055\u3044";var e=this;(function(b){var a=!1;window.addEventListener("resize",function(){"number"==typeof a&&clearTimeout(a);a=setTimeout(b,100)})})(function(){return f.OnResize.call(e)});
this.width=d;this.height=c;this.OnResize()}a.prototype.OnResize=function(b){var a=this.ctx.canvas,d=Math.min((this.Parent.clientWidth-Settings.ResizingCanvas.Margin)/this.width,(this.Parent.clientHeight-Settings.ResizingCanvas.Margin)/this.height);a.style.width=d*this.width+"px";a.style.height=d*this.height+"px";d*=b||window.devicePixelRatio||1;a.width=d*this.width;a.height=d*this.height;this.ctx.lineWidth=b||window.devicePixelRatio||1;this.scale=d};a.prototype.S=function(b){return b*this.scale};
a.prototype.Line=function(b,a,d,c){this.ctx.beginPath();this.ctx.moveTo(this.S(b+.5),this.S(a+.5));this.ctx.lineTo(this.S(d+.5),this.S(c+.5));this.ctx.stroke()};a.prototype.Round=function(b,a,d){this.ctx.arc(this.S(b),this.S(a),this.S(d),0,2*Math.PI,!1)};a.prototype.RoundedRect=function(b,a,d,c,f){b=this.S(b);a=this.S(a);d=this.S(d);c=this.S(c);f=this.S(f);this.ctx.moveTo(b,a+f);this.ctx.lineTo(b,a+c-f);this.ctx.quadraticCurveTo(b,a+c,b+f,a+c);this.ctx.lineTo(b+d-f,a+c);this.ctx.quadraticCurveTo(b+
d,a+c,b+d,a+c-f);this.ctx.lineTo(b+d,a+f);this.ctx.quadraticCurveTo(b+d,a,b+d-f,a);this.ctx.lineTo(b+f,a);this.ctx.quadraticCurveTo(b,a,b,a+f)};a.prototype.TextCenter=function(b,a,d,c){this.ctx.textAlign="center";this.ctx.textBaseline="middle";this.ctx.fillText(b,this.S(a),this.S(d),this.S(c))};a.prototype.TextLeft=function(b,a,d,c){this.ctx.textAlign="left";this.ctx.textBaseline="middle";this.ctx.fillText(b,this.S(a),this.S(d),this.S(c))};a.prototype.TextRight=function(b,a,d,c){this.ctx.textAlign=
"right";this.ctx.textBaseline="middle";this.ctx.fillText(b,this.S(a),this.S(d),this.S(c))};a.prototype.Shadow=function(){this.ctx.shadowBlur=this.S(Settings.ResizingCanvas.shadowBlur);this.ctx.shadowColor=Settings.ResizingCanvas.shadowColor;this.ctx.shadowOffsetX=this.S(Settings.ResizingCanvas.shadowOffsetX);this.ctx.shadowOffsetY=this.S(Settings.ResizingCanvas.shadowOffsetY)};return a}(),Background=function(){function a(){this.Name="Background";this.Enabled=!0;this.BeforeOpe=this.FPSspan=this.FPScount=
0;this.Countdown2Disable=Settings.Background.DisableCount}a.prototype.Init=function(b){TrafficBackground.Init(b);this.BeforeOpe=this.FPSspan=this.FPScount=0;return this};a.prototype.Draw=function(b,a){this.FPSspan+=a;if(this.FPScount++>Settings.Background.FPSspan){var d=1E3/(this.FPSspan/this.FPScount);d<Settings.Background.FPS[0]?(1==this.BeforeOpe?(console.log((d<<0)+"FPS-- => DPIfactor: "+(10*(TrafficBackground.GetDPI()-.1)<<0)),TrafficBackground.SetDPI(TrafficBackground.GetDPI()+.1),this.Countdown2Disable--,
0>this.Countdown2Disable&&(b.ctx.fillStyle=Settings.BackDrawer.Background,b.ctx.fillRect(0,0,b.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),b.S(Settings.Game.Hcell*(Settings.Game.Hcount+1))),this.Enabled=!1)):console.log((d<<0)+"FPS--"),this.BeforeOpe=1):d>Settings.Background.FPS[1]?(-1==this.BeforeOpe?(console.log((d<<0)+"FPS++ => DPIfactor: "+(10*(TrafficBackground.GetDPI()-.1)<<0)),TrafficBackground.SetDPI(TrafficBackground.GetDPI()-.1)):console.log((d<<0)+"FPS++"),this.BeforeOpe=-1):this.BeforeOpe=
0;this.FPSspan=this.FPScount=0}TrafficBackground.Tick()};return a}(),BackDrawer=function(){function a(){this.Name="Back";this.Enabled=!0}a.prototype.Draw=function(b,a){b.ctx.clearRect(0,0,b.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),b.S(Settings.Game.Hcell*(Settings.Game.Hcount+1)));b.ctx.fillStyle=Settings.BackDrawer.Background;b.ctx.strokeStyle=Settings.BackDrawer.Border;b.ctx.save();b.ctx.globalAlpha=Settings.BackDrawer.Alpha;b.ctx.fillRect(0,0,b.S(Settings.Game.Wcell*(Settings.Game.Wcount+
1)),b.S(Settings.Game.Hcell*(Settings.Game.Hcount+1)));b.ctx.restore();for(var d=1;d<Settings.Game.Wcount;d++)b.Line(d*Settings.Game.Wcell-1,1*Settings.Game.Hcell,d*Settings.Game.Wcell-1,30*Settings.Game.Hcell);b.ctx.fillStyle=Settings.BackDrawer.TextColor;b.ctx.font=(b.S(Settings.Game.Hcell-4)<<0)+"px "+Settings.Game.FontName;b.TextLeft("Life:  "+Game.life.toString(),Settings.BackDrawer.MarginLeft*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-2+.5),Settings.Game.Wcell*Settings.Game.Wcount/
2);b.TextLeft("Score: "+Game.score.toString(),Settings.BackDrawer.MarginLeft*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-1+.5),Settings.Game.Wcell*Settings.Game.Wcount/2);b.TextRight("Hint: "+Game.hintCount.toString(),(Settings.Game.Wcount-Settings.BackDrawer.MarginRight)*Settings.Game.Wcell,Settings.Game.Hcell*(Settings.Game.Hcount-1+.5),Settings.Game.Wcell*Settings.Game.Wcount/2);b.TextRight("Lv."+Game.GetLevelText(),(Settings.Game.Wcount-Settings.BackDrawer.MarginRight)*Settings.Game.Wcell,
Settings.Game.Hcell*(Settings.Game.Hcount-2+.5),Settings.Game.Wcell*Settings.Game.Wcount/2)};return a}(),Dropper=function(){function a(){this.Name="Dropper";this.Enabled=!0;this.dx=Settings.Dropper.MoveSpeed;this.x=(Settings.Game.Wcount-1)/2<<0}a.prototype.BeforeDraw=function(b,a){var d=this;this.dx=Math.sign(this.dx)*Math.min(Settings.Dropper.MaxSpeed,Settings.Dropper.MoveSpeed+(Math.max(Game.level/Settings.NumNodes.LevelToMaxWeighting,Settings.Dropper.SpeedUpLevel)-Settings.Dropper.SpeedUpLevel)/
Settings.Dropper.SpeedUpSpeed);if(this.x<<0!=this.x+this.dx*a/1E3<<0&&(this.x+=this.dx*a/1E3,Math.random()<Settings.Dropper.TurnProbability&&(this.dx*=-1),Math.random()<Settings.Dropper.DropProbability)){var c=b.find(function(b){return"NumNodes"==b.Name});if(c instanceof NumNodes)c.nums.some(function(b){return b[0]==Math.round(d.x+Settings.Game.Wcount)%Settings.Game.Wcount&&1>b[1]})||c.Add(Math.round(this.x+Settings.Game.Wcount)%Settings.Game.Wcount,0);else throw"ERROR";}};a.prototype.Draw=function(b,
a){this.x+=this.dx*a/1E3;this.x=(this.x+Settings.Game.Wcount)%Settings.Game.Wcount;b.ctx.fillStyle=Settings.Dropper.Color;b.ctx.beginPath();b.RoundedRect(this.x*Settings.Game.Wcell,0,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell);b.ctx.fill();this.x>Settings.Game.Wcount-1&&(b.ctx.beginPath(),b.RoundedRect((this.x-Settings.Game.Wcount)*Settings.Game.Wcell,0,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell),b.ctx.fill())};return a}(),Shooter=function(){function a(){this.Name=
"Shooter";this.Enabled=!0;this.Keymap=Settings.Shotter.Keymap;this.KeySleepMax1=Settings.Shotter.KeySleepMax1;this.KeySleepMax2=Settings.Shotter.KeySleepMax2;this.KeyMode=[0,0,0,0];this.dx=0;this.x=(Settings.Game.Wcount-1)/2<<0;this.y=Settings.Shotter.Y;this.BlinkCount=0}a.prototype.Init=function(b){function a(a){for(var f=c.KeyMode.map(function(){return 0}),d=b.getBoundingClientRect(),e=0;e<a.length;e++){var l=a[e].clientY-d.top,m=b.clientHeight;l<m/3?f[2]=1:l<m/3*2?f[3]=1:a[e].clientX-d.left<b.clientWidth/
2?f[0]=1:f[1]=1}for(e=0;e<f.length;e++)0==c.KeyMode[e]!=(0==f[e])&&(c.KeyMode[e]=f[e])}function d(){c.KeyMode=c.KeyMode.fill(0)}var c=this;document.addEventListener("keydown",function(a){var b=c.Keymap.findIndex(function(b){return b==a.keyCode});0>b||(a.preventDefault(),a.repeat||0==c.KeyMode[b]&&(c.KeyMode[b]=1))});document.addEventListener("keyup",function(b){var a=c.Keymap.findIndex(function(a){return a==b.keyCode});0>a||(b.preventDefault(),c.KeyMode[a]=0)});b.addEventListener("touchstart",function(b){return a(b.touches)});
b.addEventListener("touchmove",function(b){return a(b.touches)});b.addEventListener("touchend",function(b){return a(b.touches)});b.addEventListener("mousedown",function(b){b=[0,2,1][b.button];0==c.KeyMode[b]&&(c.KeyMode[b]=1)});b.addEventListener("mouseup",function(b){c.KeyMode[[0,2,1][b.button]]=0});b.addEventListener("touchcancel",d);b.addEventListener("contextmenu",function(b){return b.preventDefault()});window.addEventListener("blur",d);return this};a.prototype.BeforeDraw=function(b,a){var d=
this;this.KeyMode.forEach(function(a,f){if(0!=a&&(1==a||0==(a-d.KeySleepMax1[f])%d.KeySleepMax2[f]&&a>=d.KeySleepMax1[f]))switch(f){case 0:d.dx=-Settings.Shotter.MoveSpeed;break;case 1:d.dx=Settings.Shotter.MoveSpeed;break;case 2:b.find(function(b){return"Shots"==b.Name}).Add(Math.round(d.x+Settings.Game.Wcount)%Settings.Game.Wcount,d.y);break;case 3:b.find(function(b){return"NumNodes"==b.Name}).Hint()}},this);this.KeyMode=this.KeyMode.map(function(b){return 0==b?0:b+1})};a.prototype.Draw=function(b,
a){function d(){b.ctx.beginPath();b.ctx.moveTo(b.S((this.x+.5)*Settings.Game.Wcell-.5),b.S(this.y*Settings.Game.Hcell));b.ctx.lineTo(b.S((this.x+.5-.3)*Settings.Game.Wcell-.5),b.S((this.y+1)*Settings.Game.Hcell));b.ctx.lineTo(b.S((this.x+.5+.3)*Settings.Game.Wcell-.5),b.S((this.y+1)*Settings.Game.Hcell));b.ctx.fill()}0<this.dx&&this.x<<0!=this.x+this.dx<<0?(this.x=this.x+this.dx<<0,this.dx=0):0>this.dx&&Math.ceil(this.x)!=Math.ceil(this.x+this.dx)&&(this.x=Math.ceil(this.x+this.dx),this.dx=0);0!=
this.dx&&(this.x+=this.dx);this.x=(this.x+Settings.Game.Wcount)%Settings.Game.Wcount;b.ctx.save();this.BlinkCount=(this.BlinkCount+1)%Settings.Shotter.Beam.BlinkSpeed;b.ctx.globalAlpha=Math.sin(this.BlinkCount/Settings.Shotter.Beam.BlinkSpeed*Math.PI*2)/4+.5;b.ctx.strokeStyle=Settings.Shotter.Beam.Color;b.Line((this.x+.5)*Settings.Game.Wcell-1,1*Settings.Game.Hcell,(this.x+.5)*Settings.Game.Wcell-1,this.y*Settings.Game.Hcell);b.ctx.stroke();b.ctx.restore();b.ctx.fillStyle=Settings.Shotter.Color;d.apply(this);
this.x>Settings.Game.Wcount-1&&(this.x-=Settings.Game.Wcount,d.apply(this),this.x+=Settings.Game.Wcount)};return a}(),Shots=function(){function a(){this.Name="Shots";this.Enabled=!0;this.shots=[]}a.prototype.Add=function(b,a){this.shots.push([b,a])};a.prototype.Clear=function(){this.shots=[]};a.prototype.Draw=function(b,a){b.ctx.fillStyle=Settings.Shots.Color;b.ctx.save();b.Shadow();b.ctx.beginPath();this.shots.forEach(function(a){a[1]-=Settings.Shots.MoveSpeed;b.Round((a[0]+.5)*Settings.Game.Wcell-
.5,a[1]*Settings.Game.Hcell,Settings.Shots.Radius*Settings.Game.Hcell);b.ctx.closePath()});b.ctx.fill();b.ctx.restore()};a.prototype.AfterDraw=function(b,a){this.shots=this.shots.filter(function(b){return 0<b[1]})};return a}(),NumNodes=function(){function a(){this.Name="NumNodes";this.Enabled=!0;this.nums=[]}a.prototype.Add=function(b,a,d){if(!d)for(;;){for(var c=d=Math.max(2,Math.random()*(Settings.NumNodes.minNumber+Game.level/Settings.NumNodes.LevelToMaxWeighting)<<0),f=0;f<Settings.NumNodes.MaxFactCount;f++){c=
Factorization(c);if(0==c[0])break;c=c[1]}if(f!=Settings.NumNodes.MaxFactCount)break}this.nums.push([b,a,d?d:Math.max(2,Math.random()*Game.level/Settings.NumNodes.LevelToMaxWeighting<<0),0])};a.prototype.Hint=function(){0>=Game.hintCount||(Game.hintCount--,this.nums.forEach(function(b){0==Factorization(b[2])[0]?b[3]=1:b[3]=2}))};a.prototype.Draw=function(b,a){this.nums.forEach(function(b){return b[1]+=Settings.NumNodes.MoveSpeed});b.ctx.save();b.Shadow();for(var d=function(a){b.ctx.fillStyle=Settings.NumNodes.Colors[a];
b.ctx.beginPath();c.nums.forEach(function(f){f[3]==a&&(b.RoundedRect(f[0]*Settings.Game.Wcell,f[1]*Settings.Game.Hcell,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell),b.ctx.closePath())});b.ctx.fill()},c=this,f=0;f<Settings.NumNodes.Colors.length;f++)d(f);b.ctx.restore();b.ctx.fillStyle=Settings.NumNodes.TextColor;b.ctx.font=(b.S(Settings.Game.Hcell-4)<<0)+"px "+Settings.Game.FontName;this.nums.forEach(function(a){b.TextCenter(a[2].toString(),(a[0]+.5)*Settings.Game.Wcell,(a[1]+.5)*
Settings.Game.Hcell,Settings.Game.Wcell-4)})};a.prototype.AfterDraw=function(a,e){this.nums=this.nums.filter(function(b){if(b[1]<=Settings.Game.Hcount-3)return!0;Settings.ScoreAndLevel(1,b[2]);0!=Factorization(b[2])[0]&&a.find(function(b){return"AfterImages"==b.Name}).Add(b[0],b[1],b[2]);return!1})};return a}(),AfterImages=function(){function a(){this.Name="AfterImages";this.Enabled=!0;this.nums=[]}a.prototype.Add=function(b,a,d){this.nums.push([b,a,d,Settings.AfterImages.ShowTicks])};a.prototype.Draw=
function(b,a){this.nums.forEach(function(b){return--b[3]});b.ctx.save();b.ctx.globalCompositeOperation="lighter";b.ctx.fillStyle=Settings.AfterImages.Back;this.nums.forEach(function(a){b.ctx.globalAlpha=a[3]/Settings.AfterImages.ShowTicks*Settings.AfterImages.MaxAlpha;b.RoundedRect(a[0]*Settings.Game.Wcell,a[1]*Settings.Game.Hcell,Settings.Game.Wcell-1,Settings.Game.Hcell,Settings.Game.Rcell);b.ctx.closePath();b.ctx.fill()});b.ctx.fillStyle=Settings.AfterImages.Fore;b.ctx.font=(b.S(Settings.Game.Hcell-
4)<<0)+"px "+Settings.Game.FontName;this.nums.forEach(function(a){b.ctx.globalAlpha=a[3]/Settings.AfterImages.ShowTicks*Settings.AfterImages.MaxAlpha;b.TextCenter(a[2].toString(),(a[0]+.5)*Settings.Game.Wcell,(a[1]+.5)*Settings.Game.Hcell,Settings.Game.Wcell-4)});b.ctx.restore()};a.prototype.AfterDraw=function(a,e){this.nums=this.nums.filter(function(a){return 0<a[3]})};return a}(),Filters=function(){function a(){this.Name="Filters";this.Enabled=!0;this.filters=[]}a.prototype.Add=function(a){this.filters.push(a)};
a.prototype.Draw=function(a,e){a.ctx.strokeStyle=Settings.Filters.Color;a.ctx.save();a.Shadow();a.ctx.beginPath();this.filters.forEach(function(b){a.ctx.moveTo(0,a.S(Settings.Game.Hcell*b));a.ctx.lineTo(a.S(Settings.Game.Wcell*Settings.Game.Wcount),a.S(Settings.Game.Hcell*b))});a.ctx.stroke();a.ctx.restore()};return a}(),ButtonNodes=function(){function a(){this.Name="ButtonNodes";this.Enabled=!0;this.texts=[]}a.prototype.Add=function(a,e,d,c,f,g,k){this.texts.push({x:a,y:e,w:d,h:c,text:f,fontsize:g,
fn:k})};a.prototype.Clear=function(){this.texts=[]};a.prototype.Draw=function(a,e){a.ctx.fillStyle=Settings.ButtonNodes.Color;a.ctx.save();a.Shadow();a.ctx.beginPath();this.texts.forEach(function(b){a.RoundedRect(b.x*Settings.Game.Wcell,b.y*Settings.Game.Hcell,b.w*Settings.Game.Wcell,b.h*Settings.Game.Hcell,Settings.Game.Rcell);a.ctx.closePath()});a.ctx.fill();a.ctx.restore();a.ctx.fillStyle=Settings.ButtonNodes.TextColor;this.texts.forEach(function(b){a.ctx.font=(a.S(Settings.Game.Hcell*b.fontsize-
4)<<0)+"px "+Settings.Game.FontName;a.TextCenter(b.text,(b.x+b.w/2)*Settings.Game.Wcell,(b.y+b.h/2)*Settings.Game.Hcell,Settings.Game.Wcell*b.w-4)})};return a}(),Fading=function(){function a(){this.Name="Fading";this.Enabled=!0;this.Finished=!1;this.CurrentBrightness=0}a.prototype.Draw=function(a,e){this.CurrentBrightness>Settings.Fading.Speed?(a.ctx.fillStyle=Settings.Fading.Color,a.ctx.globalAlpha=1-this.CurrentBrightness,a.ctx.fillRect(0,0,a.S(Settings.Game.Wcell*(Settings.Game.Wcount+1)),a.S(Settings.Game.Hcell*
(Settings.Game.Hcount+1))),this.CurrentBrightness++):this.Finished=!0};return a}();
function OnhitNumShots(a,b,e){e=[];for(var d=[],c=0;c<b.shots.length&&!(0<=d.indexOf(c));c++)for(var f=0;f<a.nums.length&&!(0<=e.indexOf(f));f++)a.nums[f][0]==b.shots[c][0]&&Math.abs(a.nums[f][1]-b.shots[c][1])<.5+Settings.Shots.Radius&&(e.push(f),d.push(c));for(;0<d.length;)b.shots.splice(d.pop(),1);for(;0<e.length;)b=e.pop(),d=Factorization(a.nums[b][2]),Settings.ScoreAndLevel(2,a.nums[b][2]),0!=d[0]?(a.Add((a.nums[b][0]+Settings.Game.Wcount-1)%Settings.Game.Wcount,a.nums[b][1]-1,d[0]),a.Add((a.nums[b][0]+
Settings.Game.Wcount+1)%Settings.Game.Wcount,a.nums[b][1]-1,d[1])):Game.Elms.find(function(a){return"AfterImages"==a.Name}).Add(a.nums[b][0],a.nums[b][1],a.nums[b][2]),a.nums.splice(b,1)}
function OnhitNumNum(a,b,e){var d=[];for(b=0;b<a.nums.length&&!(0<=d.indexOf(b));b++)for(e=b+1;e<a.nums.length&&!(0<=d.indexOf(e));e++)a.nums[b][0]==a.nums[e][0]&&1>Math.abs(a.nums[b][1]-a.nums[e][1])&&(d.push(b),d.push(e));if(0!=d.length){for(b=0;b<d.length;b+=2)a.Add(a.nums[d[b]][0],(a.nums[d[b]][1]+a.nums[d[b+1]][1])/2,a.nums[d[b]][2]+a.nums[d[b+1]][2]);a.nums=a.nums.filter(function(a,b){return 0>d.indexOf(b)})}}
function OnhitFiltersNum(a,b,e){e=[];for(var d=0;d<a.filters.length;d++)for(var c=0;c<b.nums.length&&!(0<=e.indexOf(c));c++).5>Math.abs(b.nums[c][1]-a.filters[d]+.5)&&0==Factorization(b.nums[c][2])[0]&&e.push(c);for(e.sort(function(a,b){return a-b});0<e.length;)a=e.pop(),Settings.ScoreAndLevel(0,b.nums[a][2]),b.nums.splice(a,1)}
function OnhitBtnShots(a,b,e){e=[];for(var d=[],c=0;c<b.shots.length&&!(0<=d.indexOf(c));c++)for(var f=0;f<a.texts.length&&!(0<=e.indexOf(f));f++)a.texts[f].y-Settings.Shots.Radius<=b.shots[c][1]&&a.texts[f].y+a.texts[f].h+Settings.Shots.Radius>=b.shots[c][1]&&a.texts[f].x<=b.shots[c][0]&&a.texts[f].x+a.texts[f].w-1>=b.shots[c][0]&&(e.push(f),d.push(c));for(;0<d.length;)b.shots.splice(d.pop(),1);for(;0<e.length;)b=e.pop(),a.texts[b].fn()}
function onLoad(a){a.find(function(a){return"Fading"==a.Name}).Enabled=!1;a.find(function(a){return"Dropper"==a.Name}).Enabled=!1;a.find(function(a){return"NumNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Filters"==a.Name}).Enabled=!1;var b=a.find(function(a){return"ButtonNodes"==a.Name});if(b instanceof ButtonNodes)b.Add(1,1,Settings.Game.Wcount-2,3,"Prime Shooter",2,function(){return b.texts[0].text="Prime Shooter"==b.texts[0].text?"\u7d20\u6570\u30b7\u30e5\u30fc\u30c6\u30a3\u30f3\u30b0":
"Prime Shooter"}),b.Add(1,11,3,2,"Start",1.5,function(){a.find(function(a){return"Dropper"==a.Name}).Enabled=!0;a.find(function(a){return"NumNodes"==a.Name}).Enabled=!0;a.find(function(a){return"Filters"==a.Name}).Enabled=!0;a.find(function(a){return"ButtonNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Shots"==a.Name}).Clear();AddFilter(a)}),b.Add(Settings.Game.Wcount-4,11,3,2,"Help",1.5,function(){document.getElementById("help").classList.toggle("hide")});else throw"ERROR";}
function onTick(a,b){var e=Settings.onTick.HintperLevel*Settings.NumNodes.LevelToMaxWeighting,d=Settings.onTick.FilterperLevel*Settings.NumNodes.LevelToMaxWeighting;Game.level>Game.maxLevel&&(Game.level/e<<0>Game.maxLevel/e<<0&&Game.hintCount++,Game.level/d<<0>Game.maxLevel/d<<0&&AddFilter(a),Game.maxLevel=Game.level);if(0>=Game.life)if(!a.find(function(a){return"Fading"==a.Name}).Finished)a.find(function(a){return"Fading"==a.Name}).Enabled||(Game.life=0,a.find(function(a){return"Dropper"==a.Name}).Enabled=
!1,a.find(function(a){return"NumNodes"==a.Name}).Enabled=!1,a.find(function(a){return"Filters"==a.Name}).Enabled=!1,a.find(function(a){return"Fading"==a.Name}).Enabled=!0);else if(a.find(function(a){return"Fading"==a.Name}).Enabled){a.find(function(a){return"Shots"==a.Name}).shots=[];a.find(function(a){return"Fading"==a.Name}).Enabled=!1;var c=a.find(function(a){return"ButtonNodes"==a.Name});if(c instanceof ButtonNodes)c.Enabled=!0,c.Clear(),c.Add(1,1,Settings.Game.Wcount-2,3,"Gameover",2,function(){return!0}),
c.Add(2,5,Settings.Game.Wcount-4,1,"Score: "+Game.score+"pt",1,function(){return 0}),c.Add(2,6.5,Settings.Game.Wcount-4,1,"Rank: ...",1,function(){return 0}),c.Add(1.5,15,3,2,"Restart",1.5,function(){confirm("\u672c\u5f53\u306b?")&&location.reload(!0)}),c.Add(1.5,11,Settings.Game.Wcount-3,2,"Add to Ranking",1.5,function(){if(c instanceof ButtonNodes&&"Add to Ranking"==c.texts[c.texts.length-1].text){var a=prompt("Enter your name...","anonymous");if(a&&0<a.length){var b=function(){d++;c instanceof
ButtonNodes&&2==d&&(c.texts[c.texts.length-1].text="Finish!")};c.texts[c.texts.length-1].text="...";var d=0;MyStorage.Add(1,JSON.stringify({Score:Game.score,Level:Game.level,Name:a}),b);MyStorage.Add(2,JSON.stringify({Date:DateFormat(new Date),IP:IPAddress,UA:window.navigator.userAgent}),b)}}}),MyStorage.Get(1,function(a){a=a.map(function(a){return JSON.parse(a)});a=a.sort(function(a,b){return b.Score-a.Score});var b=document.getElementById("rankingList");b.innerHTML="";a.forEach(function(a,c){b.innerHTML+=
"<li><div>#"+(c+1)+"</div><div>"+a.Score+"pt</div><div>Lv."+Game.GetLevelText(a.Level)+"</div><div>"+a.Name+"</div></li>"});var f=a.findIndex(function(a){return a.Score<=Game.score})+1;0==f&&(f=a.length+1);c.texts[2].text="Rank: "+f+"/"+(a.length+1);document.getElementById("ranking").classList.remove("hide")});else throw"ERROR";}}
function AddFilter(a){var b=a.find(function(a){return"Shots"==a.Name}).shots,e=a.find(function(a){return"Shooter"==a.Name}).x;a.find(function(a){return"Dropper"==a.Name}).Enabled=!1;a.find(function(a){return"NumNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Shooter"==a.Name}).Enabled=!1;setTimeout(function(){return a.find(function(a){return"Shooter"==a.Name}).Enabled=!0},1E3);a.find(function(a){return"Shooter"==a.Name}).KeyMode=a.find(function(a){return"Shooter"==a.Name}).KeyMode.fill(0);a.find(function(a){return"Shooter"==
a.Name}).x=2;var d=a.find(function(a){return"Filters"==a.Name});d instanceof Filters&&d.Add(5);var c=a.find(function(a){return"ButtonNodes"==a.Name});if(c instanceof ButtonNodes)c.Enabled=!0,c.Clear(),c.Add(1,1,Settings.Game.Wcount-2,3,"Add Filter",2,function(){return c.texts[0].text="Add Filter"==c.texts[0].text?"13\u3063\u3066\u3044\u3044\u3088\u306d\uff01":"Add Filter"}),c.Add(1,Settings.Game.Hcount-9,1,2,"\u2191",1.5,function(){var b=a.find(function(a){return"Filters"==a.Name});b instanceof Filters&&
(b.filters[b.filters.length-1]=Math.min(Settings.Game.Hcount-5,Math.max(1,b.filters[b.filters.length-1]-1)))}),c.Add(2,Settings.Game.Hcount-9,1,2,"\u2193",1.5,function(){var b=a.find(function(a){return"Filters"==a.Name});b instanceof Filters&&(b.filters[b.filters.length-1]=Math.min(Settings.Game.Hcount-5,Math.max(1,b.filters[b.filters.length-1]+1)))}),c.Add(3,Settings.Game.Hcount-9,Settings.Game.Wcount-4,2,"Add & Start",1.5,function(){a.find(function(a){return"Dropper"==a.Name}).Enabled=!0;a.find(function(a){return"NumNodes"==
a.Name}).Enabled=!0;a.find(function(a){return"ButtonNodes"==a.Name}).Enabled=!1;a.find(function(a){return"Shots"==a.Name}).shots=b;a.find(function(a){return"Shooter"==a.Name}).x=e});else throw"ERROR";}var Game;
(function(a){a.score=0;a.level=1;a.maxLevel=0;a.life=Settings.Game.life;a.hintCount=0;var b;a.Elms=[(new Background).Init("bg"),new BackDrawer,new Dropper,,new Shots,new NumNodes,new Filters,new AfterImages,new ButtonNodes,new Fading];var e=[{Fn:OnhitBtnShots,Elm1:"ButtonNodes",Elm2:"Shots"},{Fn:OnhitNumShots,Elm1:"NumNodes",Elm2:"Shots"},{Fn:OnhitNumNum,Elm1:"NumNodes",Elm2:"NumNodes"},{Fn:OnhitFiltersNum,Elm1:"Filters",Elm2:"NumNodes"}];a.Init=function(){b=new ResizingCanvas(document.getElementById("c1"),
document.documentElement,Settings.Game.Wcell*Settings.Game.Wcount,Settings.Game.Hcell*Settings.Game.Hcount);a.Elms[3]=(new Shooter).Init(b.ctx.canvas);onLoad(a.Elms)};var d=void 0;a.Tick=function(c){void 0===d&&(d=c);a.Elms.forEach(function(b){"BeforeDraw"in b&&b.Enabled&&b.BeforeDraw(a.Elms,c-d)});a.Elms.forEach(function(a){"Draw"in a&&a.Enabled&&a.Draw(b,c-d)});a.Elms.forEach(function(b){"AfterDraw"in b&&b.Enabled&&b.AfterDraw(a.Elms,c-d)});e.forEach(function(b){var e=a.Elms.find(function(a){return a.Name==
b.Elm1});if(!e)throw"undefined node name";var f=a.Elms.find(function(a){return a.Name==b.Elm2});if(!f)throw"undefined node name";e.Enabled&&f.Enabled&&b.Fn(e,f,c-d)});d=c;onTick(a.Elms,c-d)};a.GetLevelText=function(b){void 0===b&&(b=a.level);return 0==b%Settings.NumNodes.LevelToMaxWeighting?(b/Settings.NumNodes.LevelToMaxWeighting).toString():b<Settings.NumNodes.LevelToMaxWeighting?b+"/"+Settings.NumNodes.LevelToMaxWeighting:(b/Settings.NumNodes.LevelToMaxWeighting<<0)+"+"+b%Settings.NumNodes.LevelToMaxWeighting+
"/"+Settings.NumNodes.LevelToMaxWeighting}})(Game||(Game={}));function LoadScript(a){var b=document.createElement("script");b.src=a;document.body.appendChild(b)}function DateFormat(a){var b=a.getFullYear(),e=a.getMonth()+1,d=a.getDate(),c=a.getHours(),f=a.getMinutes();a=a.getSeconds();return b+"/"+e+"/"+d+" "+c+":"+f+":"+a}var IPAddress="",AccessTime="";function AddAccessLog(a){IPAddress=a.ip;MyStorage.Add(4,AccessTime+" "+IPAddress+" "+window.navigator.userAgent,function(){return 0})}var MyStorage;
(function(a){function b(a){return"https://script.google.com/macros/s/AKfycbwgY_buxMtX3TLIxYrNfpyFZhyewRU0A3TnvDCi4A5yyY20AT0/exec?type=Get&ID="+a.toString()}function e(a,b){return"https://script.google.com/macros/s/AKfycbwgY_buxMtX3TLIxYrNfpyFZhyewRU0A3TnvDCi4A5yyY20AT0/exec?type=Add&ID="+a.toString()+"&Text="+encodeURIComponent(b)}a.GettingURL=b;a.AddingURL=e;a.Get=function(d,c){a._GetCB=c;LoadScript(b(d)+("&prefix="+encodeURIComponent("MyStorage._GetCB")))};a.Add=function(b,c,f){a._AddCB=f;LoadScript(e(b,
c)+("&prefix="+encodeURIComponent("MyStorage._AddCB")))}})(MyStorage||(MyStorage={}));var CSSloader;(function(a){a.Load=function(a){a.forEach(function(a){var b=document.createElement("link");b.type="text/css";b.rel="stylesheet";b.href=a;document.head.appendChild(b)})}})(CSSloader||(CSSloader={}));Polyfill.Do();
window.addEventListener("load",function(){function a(){Game.Tick(GetTime());requestAnimationFrame(a)}AccessTime=DateFormat(new Date);LoadScript(MyStorage.AddingURL(3,AccessTime+" "+window.navigator.userAgent)+"&prefix="+encodeURIComponent(""));LoadScript("https://api.ipify.org?format=jsonp&callback=AddAccessLog");CSSloader.Load(["https://fonts.googleapis.com/earlyaccess/notosansjapanese.css","https://fonts.googleapis.com/css?family=Open+Sans:300,700","https://fonts.googleapis.com/earlyaccess/kokoro.css",
"https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css"]);Game.Init();a()});document.body.removeChild(document.getElementById("message"));